### ISSUE TITLE
Repeated processing of response items that cause an exception

### ISSUE THREAD

**Issue by htollefsen** [transfer-framework/transfer#33]

**Comment by htollefsen** [comment]
I was gonna push transfer/ezplatform#82 forward, but realized this one needs to be solved first.
Where is this functionality prefered implemented? In the [Processor](https://github.com/transfer-framework/transfer/blob/1.0/src/Transfer/Processor/Processor.php)? 

Do you have any thoughts about how this should be implemented? 

Small suggestion:
- Implement some sort of CatchableException in Transfer so Adapter-developers can extend it, to prevent all Exceptions from being catched which might result in an endless loop.
- Catch this exception (in the Processor?) and put it back into queue/Storage(?).

**Comment by valisj** [comment]
The suggestion sounds great. There may be several ways to approach this. 

I'd go for implementing this in the [SequentialProcessor](https://github.com/transfer-framework/transfer/blob/1.0/src/Transfer/Processor/SequentialProcessor.php). Here's a rough sketch of how I would have probably modified the code:

```php
protected function handleProcedure(Procedure $procedure)
{
    foreach ((array) $procedure->getSources() as $source) {
        list($adapter, $request) = $source;
        $response = $this->handleSource($adapter, $request);
        
        $responseIterator = $response->getIterator(); // data from the source adapter
        $responseIterator->rewind();

        $delayedObjects = new InMemoryStorage(); // here we'll store the delayed objects
        $delayedIterator = new StorageIterator($storage); // StorageIterator should be implemented

        $iterator = new \AppendIterator(); // this iterator combines the two preceeding ones
        $iterator->append($responseIterator);
        $iterator->append($delayedIterator);

        while ($object = $this->nextObject($iterator)) {
            $storage = $this->prepareLocalStorage($object);
            try {
                $this->handleWorkers($procedure->getWorkers(), $storage);
            }
            catch (DelayedExecutionException $e) {
                $delayedObjects->add($object); 
                continue;
            }
            $this->handleTargets($procedure->getTargets(), new Request($storage->all()));
            $this->mergeStorage($storage);
        }
    }
}
```
