### ISSUE TITLE
[Question] Implement RequestHeaderSetterAwareInterface

### ISSUE THREAD

**Issue by htollefsen** [transfer-framework/transfer#34]
As discussed in https://github.com/transfer-framework/ezplatform/issues/93. 

Has this interface been introduced with another name maybe?

**Comment by valisj** [comment]
@htollefsen No, it hasn't. I have just read my original comment one more time and concluded that the `RequestHeaderSetterAwareInterface` approach doesn't seem to be very developer friendly. So I think we'll be better off with finding a simpler solution. Until then, let's just keep it the way it is.

**Comment by htollefsen** [comment]
> (...) doesn't seem to be very developer friendly.

Good point. Let's just leave as-is for now.
