### ISSUE TITLE
Confusing adapter names

### ISSUE THREAD

**Issue by nmeirik** [transfer-framework/transfer#4]
The concept of Input and Output adapters are slightly confusing since it presumes a context. The context is Transfer (meaning input to and output from Transfer), but this could easily be mistaken for the systems we are gettting data from and sending data to.

To combat this issue, I suggest renaming Input to Source and Output to Target to better signify their purpose.

**Comment by nmeirik** [comment]
@valisj Could I get some information about how this affects the API (and again the docs)?

**Comment by valisj** [comment]
@nmeirik All usages of Input and Output have been replaced with Source and Target. Docs are going to be published within a few days. Note that this BC break was an exception, which was made taking into the account the project's age and usage. Thus, the aliasing-and-deprecation approach was dismissed.
