### ISSUE TITLE
A worker that can split a container/iterator in storage

### ISSUE THREAD

**Issue by ghost** [transfer-framework/transfer#9]
From https://github.com/transfer-framework/commons/issues/12 by @htollefsen 

> As some source adapters or workers may return collections of data, it should be a standard way to manipulate storage.
> 
> E.g.:
> 
> A source adapter gets a list of Products from an external API
> Suggested worker should be able to split the products returned from the adapter, into several instances in the storage.
> Next worker or target adapter handles one and one instance.
> This way the next worker or target doesn't have to be implemented to handle more than one instance. > Will make it much better to make third-party adapters and integrations.

**Comment by valisj** [comment]
@htollefsen The splitter is added.

Usage:

```
         $builder
             ->addSource(function () {
                 return new Response(array(array('a', 'b', 'c')));
             })
             ->split()
             ->addWorker(function ($object) {
                 echo is_string($object); // true
             })
             ->end();
```

**Comment by htollefsen** [comment]
Great! It's perfect.
